# Generated by Django 2.0.6 on 2018-06-20 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='film',
            name='price',
            field=models.DecimalField(decimal_places=2, default='1.00', max_digits=10),
        ),
        migrations.AddField(
            model_name='film',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='film',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='film', to='films.Category'),
        ),
    ]
