# Generated by Django 2.0.6 on 2018-06-20 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0004_auto_20180620_1237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='stock',
        ),
        migrations.AddField(
            model_name='movie',
            name='film_director',
            field=models.TextField(blank=True),
        ),
    ]
