# Generated by Django 2.0.6 on 2018-06-20 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0006_movie_trailer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='available',
            new_name='after_premiere',
        ),
    ]
