# Generated by Django 2.0.6 on 2018-06-20 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0007_auto_20180620_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='film_director',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
