# Generated by Django 2.0.6 on 2018-06-20 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0008_auto_20180620_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='country_production',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='movie',
            name='film_director',
            field=models.CharField(default='', max_length=100),
        ),
    ]
